FROM docker.esbu.smartmatic.net/wildfly

ADD standalone.xml /opt/jboss/wildfly/standalone/configuration/

ADD *.jks /opt/jboss/wildfly/standalone/configuration/

#ADD app-roles.properties /opt/jboss/wildfly/standalone/configuration/
#ADD wildfly-helloworld-war-ssl.war /opt/jboss/wildfly/standalone/deployments/
